package scheduler

import (
	"testing"
	"time"

	"github.com/pokt-foundation/utils-go/logger"
	mock "github.com/stretchr/testify/mock"
)

func TestScheduler_Run(t *testing.T) {
	tests := []struct {
		name          string
		runDuration   time.Duration
		tickInterval  time.Duration
		expectedCalls int
	}{
		{
			name:          "should run scheduler for 500ms with 100ms tick interval",
			runDuration:   500 * time.Millisecond,
			tickInterval:  100 * time.Millisecond,
			expectedCalls: 5,
		},
		{
			name:          "should run scheduler for 1s with 200ms tick interval",
			runDuration:   1 * time.Second,
			tickInterval:  200 * time.Millisecond,
			expectedCalls: 5,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			mockRelayer := newMockIRelayer(t)
			mockRelayer.On("SendWSRelays").Return(nil)

			scheduler := NewScheduler(Config{
				Relayer:  mockRelayer,
				Interval: test.tickInterval,
				Logger:   logger.New(),
			})

			done := make(chan bool)
			go func() {
				scheduler.Run()
				done <- true
			}()

			time.Sleep(test.runDuration)
			close(done)

			mockRelayer.AssertNumberOfCalls(t, "SendWSRelays", test.expectedCalls)
			mockRelayer.AssertExpectations(t)
		})
	}
}

// Code below generated by mockery v2.41.0. DO NOT EDIT.

// mockIRelayer is an autogenerated mock type for the iRelayer type
type mockIRelayer struct {
	mock.Mock
}

// SendWSRelays provides a mock function with given fields:
func (_m *mockIRelayer) SendWSRelays() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendWSRelays")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockIRelayer creates a new instance of mockIRelayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockIRelayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockIRelayer {
	mock := &mockIRelayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
