package subscription

import (
	"context"
	"fmt"
	"math/rand"
	"testing"
	"time"

	"github.com/pokt-foundation/pocket-go/provider"
	"github.com/pokt-foundation/portal-http-db/v2/types"
	"github.com/pokt-foundation/portal-middleware/metrics"
	"github.com/pokt-foundation/portal-middleware/node"
	"github.com/pokt-foundation/portal-middleware/relay"
	"github.com/pokt-foundation/utils-go/logger"
	"github.com/pokt-foundation/wss-rewards/cache"

	mock "github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

func TestRelaySubscriber_Process(t *testing.T) {
	tests := []struct {
		name              string
		relayMessages     []metrics.Relay
		batchSize         int16
		expectedCallCount int
		blockAt           int // index to block at, -1 if no block
		resumeAt          int // index to resume at, -1 if no resume
	}{
		{
			name:              "should process 5000 relays and persist with batch size 100",
			relayMessages:     generateRandomWSRelays(5_000),
			batchSize:         1000,
			expectedCallCount: 5,
			blockAt:           -1,
			resumeAt:          -1,
		},
		{
			name:              "should process 12000 relays and persist with batch size 300",
			relayMessages:     generateRandomWSRelays(12_000),
			batchSize:         3000,
			expectedCallCount: 4,
			blockAt:           -1,
			resumeAt:          -1,
		},
		{
			name:              "should block and then resume processing relays",
			relayMessages:     generateRandomWSRelays(1_000),
			batchSize:         100,
			expectedCallCount: 10,
			blockAt:           300, // Block after 300 messages
			resumeAt:          700, // Resume after 700 messages
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := require.New(t)

			mockCache := newMockICache(t)
			blockCh := make(chan struct{})
			resumeCh := make(chan struct{})

			rs, err := NewRelaySubscriber(RelaySubscriberConfig{
				Cache:     mockCache,
				BatchSize: test.batchSize,
				BlockCh:   blockCh,
				ResumeCh:  resumeCh,
				Logger:    logger.New(),
			})
			c.NoError(err)

			relayCh := make(chan metrics.Relay, len(test.relayMessages))
			defer close(relayCh)

			rs.relayCh = relayCh

			// Split relayMessages into batches and generate expectedRelaysMap for each batch
			for i := 0; i < test.expectedCallCount; i++ {
				startIndex := i * int(test.batchSize)
				endIndex := startIndex + int(test.batchSize)
				if endIndex > len(test.relayMessages) {
					endIndex = len(test.relayMessages)
				}
				batch := test.relayMessages[startIndex:endIndex]
				expectedRelaysMap := generateExpectedRelaysMap(batch)

				// Expect SetWSRelays to be called with the expectedRelaysMap
				mockCache.On("SetWSRelays", expectedRelaysMap).Return(nil).Run(func(args mock.Arguments) {
					arg := args.Get(0).(map[cache.NodeKey]int64)
					c.Equal(expectedRelaysMap, arg)
				}).Once()
			}

			// Run Process in a goroutine to allow blocking and resuming
			go rs.Process(context.Background())

			for i, relay := range test.relayMessages {
				if i == test.blockAt {
					blockCh <- struct{}{}
				}
				if i == test.resumeAt {
					resumeCh <- struct{}{}
				}
				relayCh <- relay
			}

			// Wait for the Process to finish
			<-time.After(2 * time.Second)

			// Check if the expected number of calls to SetWSRelays matches
			mockCache.AssertNumberOfCalls(t, "SetWSRelays", test.expectedCallCount)
			mockCache.AssertExpectations(t)
		})
	}
}

func generateRandomWSRelays(n int) []metrics.Relay {
	nodes := make([]node.V0Node, 5)
	for i := range nodes {
		nodes[i] = node.V0Node{
			ProviderNode: provider.Node{PublicKey: fmt.Sprintf("node_%d", i)},
		}
	}

	chains := make([]types.RelayChainID, 9)
	for i := range chains {
		chains[i] = types.RelayChainID(fmt.Sprintf("W00%d", i))
	}

	apps := make([]types.PortalAppLite, 8)
	for i := range apps {
		apps[i] = types.PortalAppLite{ID: types.PortalAppID(fmt.Sprintf("app_%d", i))}
	}

	metadata := make([]metrics.Relay, n)
	for i := 0; i < n; i++ {
		metadata[i] = metrics.Relay{
			PoktNodePublicKey: string(nodes[rand.Intn(len(nodes))].ID()),
			PoktChainID:       chains[rand.Intn(len(chains))],
			RelayRequest:      metrics.RelayRequest{Details: relay.RelayDetails{UserApplication: apps[rand.Intn(len(apps))]}},
		}
	}

	return metadata
}

func generateExpectedRelaysMap(relays []metrics.Relay) map[cache.NodeKey]int64 {
	expectedRelaysMap := make(map[cache.NodeKey]int64)
	for _, relay := range relays {
		key := cache.NodeKey{
			NodeID:      node.ID(relay.PoktNodePublicKey),
			ChainID:     relay.PoktChainID,
			PortalAppID: relay.RelayRequest.Details.UserApplication.ID,
		}
		expectedRelaysMap[key]++
	}
	return expectedRelaysMap
}

// Code below generated by mockery v2.41.0. DO NOT EDIT.

// mockCache is an autogenerated mock type for the cache type
type mockICache struct {
	mock.Mock
}

// SetWSRelays provides a mock function with given fields: _a0
func (_m *mockICache) SetWSRelays(_a0 map[cache.NodeKey]int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetWSRelays")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[cache.NodeKey]int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockCache creates a new instance of mockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockICache(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockICache {
	mock := &mockICache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
