package subscription

import (
	"context"
	"fmt"
	"math/rand"
	"sync"
	"testing"

	"github.com/pokt-foundation/pocket-go/provider"
	"github.com/pokt-foundation/portal-http-db/v2/types"
	"github.com/pokt-foundation/portal-middleware/node"
	"github.com/pokt-foundation/utils-go/logger"
	"github.com/pokt-foundation/wss-rewards/messenger"
	mock "github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

func TestRelaySubscriber_Process(t *testing.T) {
	tests := []struct {
		name              string
		relayMessages     []messenger.WSMetadata
		batchSize         int16
		expectedCallCount int
	}{
		{
			name:              "should process 5000 relays and persist with batch size 100",
			relayMessages:     generateRandomWSMetadata(5_000),
			batchSize:         1_000,
			expectedCallCount: 5,
		},
		{
			name:              "should process 12000 relays and persist with batch size 300",
			relayMessages:     generateRandomWSMetadata(12_000),
			batchSize:         3_000,
			expectedCallCount: 4,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			c := require.New(t)

			mockCache := newMockICache(t)

			relayCh := make(chan messenger.WSMetadata, len(test.relayMessages))
			for _, relay := range test.relayMessages {
				relayCh <- relay
			}
			close(relayCh)

			rs, err := NewRelaySubscriber(RelaySubscriberConfig{
				Cache:     mockCache,
				BatchSize: test.batchSize,
				Mutex:     &sync.Mutex{},
				Logger:    logger.New(),
			})
			c.NoError(err)

			rs.relayCh = relayCh

			// Split relayMessages into batches and generate expectedRelaysMap for each batch
			for i := 0; i < test.expectedCallCount; i++ {
				startIndex := i * int(test.batchSize)
				endIndex := startIndex + int(test.batchSize)
				if endIndex > len(test.relayMessages) {
					endIndex = len(test.relayMessages)
				}
				batch := test.relayMessages[startIndex:endIndex]
				expectedRelaysMap := generateExpectedRelaysMap(batch)

				// Expect SetWSRelays to be called with the expectedRelaysMap
				mockCache.On("SetWSRelays", expectedRelaysMap).Return(nil).Run(func(args mock.Arguments) {
					arg := args.Get(0).(map[NodeKey]int64)
					c.Equal(expectedRelaysMap, arg)
				}).Once()
			}

			// Run Process
			rs.Process(context.Background())

			mockCache.AssertNumberOfCalls(t, "SetWSRelays", test.expectedCallCount)
			mockCache.AssertExpectations(t)
		})
	}
}

func generateRandomWSMetadata(n int) []messenger.WSMetadata {
	nodes := make([]node.V0Node, 5)
	for i := range nodes {
		nodes[i] = node.V0Node{
			ProviderNode: provider.Node{PublicKey: fmt.Sprintf("node_%d", i)},
		}
	}

	chains := make([]types.RelayChainID, 10)
	for i := range chains {
		chains[i] = types.RelayChainID(fmt.Sprintf("chain_%d", i))
	}

	apps := make([]types.PortalAppLite, 8)
	for i := range apps {
		apps[i] = types.PortalAppLite{ID: types.PortalAppID(fmt.Sprintf("app_%d", i))}
	}

	metadata := make([]messenger.WSMetadata, n)
	for i := 0; i < n; i++ {
		metadata[i] = messenger.WSMetadata{
			Node:      nodes[rand.Intn(len(nodes))],
			ChainID:   chains[rand.Intn(len(chains))],
			PortalApp: apps[rand.Intn(len(apps))],
		}
	}

	return metadata
}

func generateExpectedRelaysMap(relays []messenger.WSMetadata) map[NodeKey]int64 {
	expectedRelaysMap := make(map[NodeKey]int64)
	for _, relay := range relays {
		key := NodeKey{
			NodeID:      relay.Node.ID(),
			ChainID:     relay.ChainID,
			PortalAppID: relay.PortalApp.ID,
		}
		expectedRelaysMap[key]++
	}
	return expectedRelaysMap
}

// Code below generated by mockery v2.41.0. DO NOT EDIT.

// mockCache is an autogenerated mock type for the cache type
type mockICache struct {
	mock.Mock
}

// SetWSRelays provides a mock function with given fields: _a0
func (_m *mockICache) SetWSRelays(_a0 map[NodeKey]int64) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetWSRelays")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[NodeKey]int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockCache creates a new instance of mockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockICache(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockICache {
	mock := &mockICache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
